name: user_repository
decsription: The Repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  
