// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcE7Gnlgaw3gKBtlEnqf5QeBDvpscQUYk',
    appId: '1:76177343192:web:d591b66571b6f586c08dad',
    messagingSenderId: '76177343192',
    projectId: 'my-task-list-block-firebase',
    authDomain: 'my-task-list-block-firebase.firebaseapp.com',
    storageBucket: 'my-task-list-block-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSms8_ewtC7WsFK9jSbwTe_A7eeo_Pfus',
    appId: '1:76177343192:android:7e0237b9d3619b31c08dad',
    messagingSenderId: '76177343192',
    projectId: 'my-task-list-block-firebase',
    storageBucket: 'my-task-list-block-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD66omX42FWhc_nc-mekk8pgJKnjgnhOtE',
    appId: '1:76177343192:ios:1a1520c607714364c08dad',
    messagingSenderId: '76177343192',
    projectId: 'my-task-list-block-firebase',
    storageBucket: 'my-task-list-block-firebase.appspot.com',
    iosBundleId: 'com.example.taskList',
  );
}
